level: INFO

entryPoints:
  web:
    # HTTP for Django
    address: ':80'
  flower:
    # HTTP for Flower
    address: ':5555'

http:
  routers:
    django-router:
      # No Host rule to allow access via IP
      rule: 'PathPrefix(`/`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django
    flower-router:
      # No Host rule to allow access via IP
      rule: 'PathPrefix(`/`)'
      entryPoints:
        - flower
      service: flower

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/middlewares/http/headers/#hostsproxyheaders
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000
    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

networks:
  traefik-public:
    external: true
