# Generated by Django 5.1.11 on 2025-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_type', models.CharField(blank=True, max_length=100)),
                ('years_code_pro', models.FloatField(blank=True, null=True)),
                ('years_of_coding', models.FloatField(blank=True, null=True)),
                ('converted_comp_yearly', models.FloatField(blank=True, null=True)),
                ('ed_level', models.CharField(blank=True, max_length=100)),
                ('countries', models.TextField(blank=True)),
                ('programming_languages', models.TextField(blank=True)),
                ('ai_select', models.CharField(blank=True, choices=[('Yes', 'Using AI'), ('No, but I plan to soon', 'Planning to Use AI'), ('No', 'Not Using AI')], max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('platforms', models.TextField(blank=True)),
                ('remote_work', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
