# Generated by Django 5.1.11 on 2025-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developersurvey',
            name='remote_work',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
