services:
  docs:
    image: salary_predictor_local_docs
    container_name: salary_predictor_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./salary_predictor:/app/salary_predictor:z
    ports:
      - '9000:9000'
    command: /start-docs
