volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

  production_redis_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    networks:
      - traefik-public
      - default

    image: salary_predictor_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: salary_predictor_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - traefik-public

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: salary_predictor_production_traefik
    depends_on:
      - django
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'
    networks:
      - traefik-public

  redis:
    image: docker.io/redis:6

    networks:
      - traefik-public

    volumes:
      - production_redis_data:/data


  celeryworker:
    <<: *django
    image: salary_predictor_production_celeryworker
    command: /start-celeryworker
    networks:
      - traefik-public

  celerybeat:
    <<: *django
    image: salary_predictor_production_celerybeat
    command: /start-celerybeat
    networks:
      - traefik-public

  flower:
    <<: *django
    image: salary_predictor_production_flower
    command: /start-flower
    networks:
      - traefik-public

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

networks:
  traefik-public:
    name: traefik-public
